/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

/**
 * 覆盖常见/边界类型映射：Option、数组、对象 JSON、默认参数。
 */
describe('CangjieTurboModuleCodeGenerator type mappings', () => {
  let tmpDir: tmp.DirResult | null = null;

  beforeEach(() => {
    tmpDir = tmp.dirSync({ unsafeCleanup: true });
  });

  afterEach(() => {
    tmpDir = null;
  });

  it('generates expected conversions for common TurboModule signatures', () => {
    const tempDirPath = tmpDir!.name;
    const specPath = path.join(tempDirPath, 'NativeSampleSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  getPrefetchResult(uri: string): string | undefined
  getSize(uri: string): Promise<number[]>
  getSizeWithHeaders(uri: string, headers: Object): Promise<Object>
  prefetchImage(uri: string, requestId: number = 0): Promise<boolean>
  abortPrefetch(requestId: number): void
  prefetchImageWithMetadata(uri: string, queryRootName: string, rootTag: number): Promise<boolean>
  queryCache(uris: Array<string>): Promise<Object>
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([
      new AbsolutePath(specPath),
    ]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tempDirPath);
    const generator = new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );

    const files = generator.generate(schema);
    const cangjieFilePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'SampleTurboModule.cj')
      .getValue();
    const cangjieBridgePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'bridge.cj')
      .getValue();
    const cppFilePath = outputRoot
      .copyWithNewSegment('cpp', 'SampleTurboModule.cpp')
      .getValue();

    const getContent = (filePath: string) =>
      [...files.entries()].find(
        ([entryPath]) => entryPath.getValue() === filePath
      )?.[1] ?? '';

    const cangjieContent = getContent(cangjieFilePath);
    const cangjieBridgeContent = getContent(cangjieBridgePath);
    const cppContent = getContent(cppFilePath);

    expect(cangjieContent).toContain('getPrefetchResult(uri: String): ?String');
    expect(cangjieContent).toContain('getSize(uri: String): Array<Float64>');
    expect(cangjieContent).toContain(
      'getSizeWithHeaders(uri: String, headers: String): String'
    );
    expect(cangjieContent).toContain('queryCache(uris: Array<String>): String');

    expect(cangjieBridgeContent).toContain('if (let Some(value) <- result)');
    expect(cangjieBridgeContent).toContain('let resultJsonArray = JsonArray()');
    expect(cangjieBridgeContent).toContain('JsonFloat');
    expect(cangjieBridgeContent).toContain('PromiseResolve(promise, resultJsonArray)');
    expect(cangjieBridgeContent).toContain('readValue<Array<String>>()');
    expect(cangjieBridgeContent).toContain('PromiseResolveJson');

    expect(cppContent).toContain('double requestId = 0.0');
    expect(cppContent).toContain('if (count > 1 && args[1].isNumber())');
    expect(cppContent).toContain('headersJsonDefaultValue = "{}"');
    expect(cppContent).toContain('urisJsonDefaultValue = "[]"');
  });
});
