/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree.
 */

import fs from 'fs';
import path from 'path';
import tmp from 'tmp';
import { AbsolutePath } from '../src/core';
import { UberSchema } from '../src/codegen';
import { CangjieTurboModuleCodeGenerator } from '../src/codegen-cangjie';

describe('CangjieTurboModuleCodeGenerator', () => {
  it('generates Cangjie and C++ templates for turbo modules', () => {
    const tmpDir = tmp.dirSync().name;
    const specPath = path.join(tmpDir, 'NativeSampleSpec.ts');
    fs.writeFileSync(
      specPath,
      `
import type { TurboModule } from 'react-native/Libraries/TurboModule/RCTExport';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  getValue(id: number, label: string): Promise<string>;
  flush(): void;
}

export default TurboModuleRegistry.get<Spec>('Sample')!;
`
    );

    const uberSchema = UberSchema.fromSpecFilePaths([
      new AbsolutePath(specPath),
    ]);
    const [schema] = uberSchema.findAllSpecSchemasByType('NativeModule');
    const outputRoot = new AbsolutePath(tmpDir);
    const generator = new CangjieTurboModuleCodeGenerator(
      outputRoot.copyWithNewSegment('cpp'),
      outputRoot.copyWithNewSegment('cpp-bridge'),
      outputRoot.copyWithNewSegment('cangjie'),
      'reactnative_ohcj.TestPackage.turboModules',
      ['Generated by Cangjie codegen test']
    );

    const files = generator.generate(schema);
    const cangjieFilePath = outputRoot
      .copyWithNewSegment('cangjie', 'Sample', 'SampleTurboModule.cj')
      .getValue();
    const cppFilePath = outputRoot
      .copyWithNewSegment('cpp', 'SampleTurboModule.cpp')
      .getValue();

    const cangjieContent = [...files.entries()].find(
      ([filePath]) => filePath.getValue() === cangjieFilePath
    )?.[1];
    const cppContent = [...files.entries()].find(
      ([filePath]) => filePath.getValue() === cppFilePath
    )?.[1];

    expect(cangjieContent).toContain(
      'package reactnative_ohcj.TestPackage.turboModules.Sample'
    );
    expect(cangjieContent).toContain('public class SampleTurboModule');
    expect(cppContent).toContain('isCjSampleEnabled');
    expect(cppContent).toContain('getValue');
  });
});
